# Node.js CI Workflow
name: Node.js CI
permissions:
    contents: read

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: test
            CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - run: npm i
            - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            - run: chmod +x ./cc-test-reporter
            - run: ./cc-test-reporter before-build
            - run: npm run cover
            - run: touch mcg.config.js
            - run: ./cc-test-reporter after-build
              if: github.event_name != 'pull_request'
